finished
Alex-javac/LibraryProject pull request #1
Opened 2021-05-13 14:11 UTC by Alex-javac

2021-05-13 15:00 UTC, RomanKashenok requested changes

2021-05-13 15:00 UTC, RomanKashenok commented on src/main/java/info/library/service/FillingDatabase.java
> +        Files.walkFileTree(Paths.get("/home/alexander/IdeaProjects/LibraryProject/src/main/java/files"), new MyFileVisitor());
1. А если в папке будет не xml файл?
2. Все книги должны бы по хорошему лежать в одном xml (обычно в реальной библиотеке больше 6 книг. И даже больше 7 000 книг)

2021-05-13 15:00 UTC, RomanKashenok commented on src/main/java/info/library/service/ValidationChecker.java
> +            SchemaFactory factory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
Для каждого файла с книгой у тебя будет создаваться новая фабрика, новая схема и весь процесс будет проходить столько раз, сколько будет книг

2021-05-13 15:00 UTC, RomanKashenok commented on src/main/java/info/library/service/JaxbCreate.java
> +            JAXBContext context = JAXBContext.newInstance(Book.class);
Тоже самое, что и для процсса валидации

2021-05-13 15:00 UTC, RomanKashenok commented on src/main/java/info/library/Runner.java
> +            FillingDatabase.fillIn();
Лучше сделай объект с уже готовыми фабриками и че ты там еще создаешь на каждый инсерт книги

2021-05-13 15:00 UTC, RomanKashenok commented on src/main/java/info/library/application/Application.java
> +                    sortBooks(service);
ты должен не сервис передавать в метод, а вызывать метод сервиса

2021-05-13 15:00 UTC, RomanKashenok commented on src/main/java/info/library/application/Application.java
> +            Scanner scanner = new Scanner(System.in);
сканер надо закрывать

2021-05-13 15:00 UTC, RomanKashenok commented on src/main/java/info/library/application/Application.java
> +    private static boolean yesNo() {
над названиями методов стоит подумать лучше

2021-05-13 15:00 UTC, RomanKashenok commented on src/main/java/info/library/application/Application.java
> +        Scanner scanner = new Scanner(System.in);
Такими темпами у тебя сканеров в приложении будет мильён

2021-05-13 15:32 UTC, Alex-javac commented on src/main/java/info/library/service/FillingDatabase.java
> +        Files.walkFileTree(Paths.get("/home/alexander/IdeaProjects/LibraryProject/src/main/java/files"), new MyFileVisitor());
если в папке будут другие файлы он их пропустит. 
логика в классе MyFileVisitor

2021-05-13 16:54 UTC, Alex-javac commented on src/main/java/info/library/application/Application.java
> +            Scanner scanner = new Scanner(System.in);
исправил

2021-05-13 16:55 UTC, Alex-javac commented on src/main/java/info/library/application/Application.java
> +        Scanner scanner = new Scanner(System.in);
устранил по максимуму)))

2021-05-13 17:26 UTC, Alex-javac commented on src/main/java/info/library/application/Application.java
> +                    sortBooks(service);
создал еще один сервис

2021-05-13 17:27 UTC, Alex-javac commented on src/main/java/info/library/application/Application.java
> +    private static boolean yesNo() {
не уверен что норм но исправил)

2021-05-13 17:28 UTC, Alex-javac commented on src/main/java/info/library/service/ValidationChecker.java
> +            SchemaFactory factory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
вынес из метода

2021-05-13 17:28 UTC, Alex-javac commented on src/main/java/info/library/service/JaxbCreate.java
> +            JAXBContext context = JAXBContext.newInstance(Book.class);
так же вынес из метода

2021-05-13 17:31 UTC, Alex-javac commented on src/main/java/info/library/service/FillingDatabase.java
> +        Files.walkFileTree(Paths.get("/home/alexander/IdeaProjects/LibraryProject/src/main/java/files"), new MyFileVisitor());
не смог разобраться с xsd 
и unmarshaller так как он у меня принимает не пачками а по 1 файлу

2021-05-13 17:33 UTC, Alex-javac commented on src/main/java/info/library/Runner.java
> +            FillingDatabase.fillIn();
они уже добавлены он просто проверяет (если появится новый файл он его добавит)

2021-05-13 18:19 UTC, Alex-javac commented on src/main/java/info/library/application/Application.java
> +        Scanner scanner = new Scanner(System.in);
в некоторых местах пришлось вернуть сканеры так как начали валиться ошибки
https://coderoad.ru/26245468/%D0%A7%D1%82%D0%BE-%D0%B4%D0%B5%D0%BB%D0%B0%D0%B5%D1%82-scanner-close
если верить этой ссылки то закрывать  сканер надо только в конце если используешь System.in

2021-05-14 06:12 UTC, RomanKashenok approved these changes
Поправь сканеры :)

2021-05-14 06:12 UTC, RomanKashenok commented on src/main/java/info/library/Runner.java
> +        ApplicationService service = new ApplicationServiceImpl();
Почему ты здесь сервис создаешь? Ты его создаешь просто что бы отдать работать в другой класс - создавай его там

2021-05-14 06:12 UTC, RomanKashenok commented on src/main/java/info/library/service/ApplicationServiceImpl.java
> +        Scanner scanner = new Scanner(System.in);
У тебя по прежнему куча не закрытых сканеров.
Если так хочется отдельный для класса - создай его как поле класса, а не создавай в каждом методе

2021-05-14 06:12 UTC, RomanKashenok commented on src/main/java/info/library/service/FillingDatabase.java
> +        Files.walkFileTree(Paths.get("/home/alexander/IdeaProjects/LibraryProject/src/main/java/files"), new MyFileVisitor());
Ну вот было бы очень неплохо все же разобраться с xsd. И, как я уже писал, по хорошему, в одном xml должны все книги находиться

2021-05-18 20:25 UTC, RomanKashenok approved these changes
ApplicationServiceImpl.java - по прежнему куча сканеров создается
Не совсем корректный маппинг - в системе у тебя Книга у которой автор - Строка, а в базе - книга, у которой автор - ссылка на таблицу с авторами, т.е. ссылка на автора, у которого есть свой id и свое имя.

Кароч работает иладно

2021-05-18 20:25 UTC, RomanKashenok commented on src/main/java/info/library/model/books/Book.java
> +    private String author;
По хорошему Автор тоже должен быть объектом

2021-05-23 05:54 UTC, merged